<?php

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_nativeZoom = false;
?>

<?php /* --------- jqZoom --------- */ ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" id="Zoomer" class="MagicZoomPlus" rel="opacity-reverse:true;background-opacity: 30; zoom-fade:true;thumb-change:mouseover;">
                <?php
                    $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(370).'" height="370" width="370" alt="'.$this->htmlEscape($_product->getImageLabel()).'" title="'.$this->htmlEscape($_product->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image-thumb');
                ?>
            </a>

<?php $firstthumbnail = '<li><a href="' . $this->helper('catalog/image')->init($_product, 'image') .'" rel="zoom-id:Zoomer" rev="' . $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(1)->resize(370) . '" title="' . $this->htmlEscape($this->getLabel()) . '"><img src="'. $this->helper('catalog/image')->init($_product, 'image')->resize(56).'" width="56" height="56"/></a></li>'; ?>
<div id="Hover" style="width:160px;float:left;"><?php echo $this->__('Roll ON to ZOOM IN'); ?></div><div id="Unhover" style="display:none; width:160px; float:left;"><?php echo $this->__('Roll OFF to zoom OUT'); ?></div><a href="#" class="ExpandBig" onclick="MagicThumb.expand(document.getElementById('Zoomer'));return false;"><?php echo $this->__('View lager'); ?></a>

<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
     <?php if($firstthumbnail) echo $firstthumbnail; ?>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="zoom-id:Zoomer" rev="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->constrainOnly(1)->resize(370); ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
